sudo: required
dist: trusty
language: c
compiler:
  - gcc
cache:
  directories:
    - "${HOME}/persist"

before_script:
# Extra gcc versions
  # For teensy build
  - sudo apt-get install gcc-arm-linux-gnueabihf
  - sudo apt-get install git-core
  - alias gcc="arm-linux-gnueabihf-gcc"
  - git clone git://git.drogon.net/wiringPi
  - cd wiringPi
  - git pull origin
  - ./build
  - pwd
script:
  - cd ..
  - gcc -I/home/travis/build/hristoandreev/MB1502-raspberry-pi/wiringPi/wiringPi main.c -o spi_synth -lwiringPi
after_failure:
