sudo: required
dist: trusty
language: c
compiler:
  - arm-linux-gnueabihf-gcc
cache:
  directories:
    - "${HOME}/persist"

before_script:
# Extra gcc versions
  # For teensy build
  - sudo apt-get install gcc-arm-linux-gnueabihf
  - sudo apt-get install git-core
  - git clone git@github.com:hristoandreev/WiringPi.git wiringPi
  - cd wiringPi
  - git pull origin
  - ./build
  - pwd
script:
  - cd ..
  - $CC -I/home/travis/build/hristoandreev/MB1502-raspberry-pi/wiringPi/wiringPi main.c -o spi_synth -lwiringPi
after_failure:
